### ISSUE TITLE
Make frequency reporting configurable

### ISSUE THREAD

**Issue by cimi** [fuioreaa/karma-better-benchmark-reporter#2]
It's nice that you automatically flip between `ops/sec` and `ops/hour` depending on the frequency of operation. However, it would be nice to have the format configurable. 

Some people might not want to floor the value, maybe they would prefer having `ops/sec` across the board with a configurable number of decimal places. I'm not sure what jsPerf expected and I can't easily find out, it being dead and all.

You could leave automatic as a default if no format is specified and allow setting a number format and interval for people who want to enforce consistency.

**Comment by fuioreaa** [comment]
I've added 3 interval options: seconds(sec), minutes(min) and hour. There's a new config example in the docs. 

The defaults are ops/sec, with no decimals. 

If you have another configuration in mind, let me know and I'll reopen.
